# Generated by Django 4.2 on 2023-05-05 23:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, periods, underscores, and hyphens.', regex='^[a-zA-Z0-9._-]+$')], verbose_name='Username')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('address1', models.CharField(blank=True, max_length=100, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=10, verbose_name='State')),
                ('zip_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Zip code must be in the format XXXXX or XXXXX-XXXX.', regex='^\\d{5}(?:[-\\s]\\d{4})?$')], verbose_name='Zip Code')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=500, verbose_name='Bio')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='mainsite.user')),
            ],
        ),
    ]
