# Generated by Django 4.2 on 2023-05-05 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='firstname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='lastname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Zip code must be in the format XXXXX or XXXXX-XXXX.', regex='^\\d{5}(?:[-\\s]\\d{4})?$')], verbose_name='zip'),
        ),
    ]
