# Generated by Django 4.2 on 2023-04-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
